### ISSUE TITLE
Does not work when using a change event

### ISSUE THREAD

**Issue by ChristophP** [spring-media/react-shadow-dom-retarget-events#1]
Hi there,

we just ran into the same problem with react not firing events in the shadow dom and tried your fix. When we tried your solution events still did not fire. From what I can tell the differences to the example you have given are:
1. We use v1 custom elements with this (`customElements.define('some-component', someComponent)`), so we called intialized it like this
```js
   connectedCallback() {
     retargetEvents(this.shadowRoot);
   }
```
2. We did not add a `mountPoint` to the shadow dom but rendered directly into the shadowRoot like
`ReactDOM.render(SomeComponent, this.shadowRoot)`
3. We fired a `change` event on an `input`

Do you have any thoughts or tipps on this?

**Comment by ChristophP** [comment]
Ah seems like number 3 is the issue because `change` isn't in your event list. Is there any reason why you only have mouse events in that list?

**Comment by LukasBombach** [comment]
Hey there, this should be fixed now

**Comment by LukasBombach** [comment]
(With version react-shadow-dom-retarget-events@1.0.6)
