### ISSUE TITLE
onSelect not firing

### ISSUE THREAD

**Issue by frontendphil** [spring-media/react-shadow-dom-retarget-events#3]
Hey there, 

I'm currently trying to map out an example on how to use our lib [react-mentions](https://github.com/effektif/react-mentions) inside a shadow dom. However, we rely on the `onSelect` event being triggered. Even though this is on your list, I believe react actually does quite [some special handling around it](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/eventPlugins/SelectEventPlugin.js). Most importantly I think they are doing some transformation from `selectionchange` to `select`. Is this known to you? You know any workaround?

**Comment by carlotapia** [comment]
Bump :)

**Comment by LukasBombach** [comment]
Hey, should be fixed now (version 1.0.6)

**Comment by LukasBombach** [comment]
It is to be noted that this is still experimental and needs to be battle-tested. I highly appreciate when you use it and report bugs. Please tell me of onSelect still doesn't work as you'd expect it.
