### ISSUE TITLE
TypeError: event.path is undefined on Firefox

### ISSUE THREAD

**Issue by samuelalvin** [spring-media/react-shadow-dom-retarget-events#6]
This issue is reproduced in Firefox. It is not reproduced in Chrome (this library works like a charm in Chrome).

By reading [this](https://stackoverflow.com/a/39245638/6638533) answer, it seems that Firefox doesn't support `event.path` which is used in this library on `index.js: line 28`.

Even though the error occurs, the app (my app, which is a simple react component inside a webcomponents custom element) still works in Firefox.

Maybe adding a custom [`getPath()` function](https://stackoverflow.com/a/45061945/6638533) for browser which doesn't support `event.path` would be suffice?

**Comment by LukasBombach** [comment]
Sorry I have reacted so late but it's merged, thank you for the PR!
